
spring.application.name=entrevistaIA

spring.datasource.url=postgresql://postgres:atNm+fV-8z$3gEt@db.zvoqvwggdfgjovqancby.supabase.co:5432/postgres

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

groq.api.key=${GROQ_API_KEY}
groq.api.url=https://api.groq.com/openai/v1/chat/completions
groq.model=llama-3.3-70b-versatile

server.port=${PORT:8080}